# Generated by scripts/update.sh from the v0.1.2 release; do not edit by hand.
class Siltide < Formula
  desc "Terminal monitor for GPUs, NPUs, and other AI accelerators"
  homepage "https://github.com/moezdil/siltide"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/moezdil/siltide/releases/download/v0.1.2/siltide-darwin-arm64"
      sha256 "43ffcde0b6d265c22cf75144f5239a6e602f88ed6f7ee281153d1c1325c66699"
    end
    on_intel do
      url "https://github.com/moezdil/siltide/releases/download/v0.1.2/siltide-darwin-amd64"
      sha256 "ef933179834250e0274994fe4e2c3d5a8f0abd94ff2e6aa6ebe306888c97e533"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/moezdil/siltide/releases/download/v0.1.2/siltide-linux-arm64"
      sha256 "7fb13072bb2e3a44791eb9812d0db44c520063ec3abb164a41c09ac690bff75e"
    end
    on_intel do
      url "https://github.com/moezdil/siltide/releases/download/v0.1.2/siltide-linux-amd64"
      sha256 "5101296e82b226347acaf5643d95eb131ea99aa4b9c742bf8c538555ac81236e"
    end
  end

  def install
    binary = Dir["siltide-*"].first
    chmod 0755, binary
    bin.install binary => "siltide"
    generate_completions_from_executable(bin/"siltide", "--completion")
    (man1/"siltide.1").write Utils.safe_popen_read(bin/"siltide", "--man")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/siltide --version")
    assert_match "siltide", shell_output("#{bin}/siltide --demo --once")
  end
end
