# Generated by scripts/update.sh from the v0.1.3 release; do not edit by hand.
class Siltide < Formula
  desc "Terminal monitor for GPUs, NPUs, and other AI accelerators"
  homepage "https://github.com/moezdil/siltide"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/moezdil/siltide/releases/download/v0.1.3/siltide-darwin-arm64"
      sha256 "866d62a1d267b5c0cb21814a8118c54936f8bc244552e56fdc768211623cb97c"
    end
    on_intel do
      url "https://github.com/moezdil/siltide/releases/download/v0.1.3/siltide-darwin-amd64"
      sha256 "83b61fb234d8ea4edff6ac27721a208d3afaaa1ca83f24a1c8f4a56ac679277e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/moezdil/siltide/releases/download/v0.1.3/siltide-linux-arm64"
      sha256 "ddfc956f56b9998e6c3a1cd5c38a63a4c933c9586ce646d00979a6e9ace4ec0b"
    end
    on_intel do
      url "https://github.com/moezdil/siltide/releases/download/v0.1.3/siltide-linux-amd64"
      sha256 "683fa2e1d8a53a64669c8436eca8ded2360845ecd81efa4095182ae982cefa8c"
    end
  end

  def install
    binary = Dir["siltide-*"].first
    chmod 0755, binary
    bin.install binary => "siltide"
    generate_completions_from_executable(bin/"siltide", "--completion")
    (man1/"siltide.1").write Utils.safe_popen_read(bin/"siltide", "--man")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/siltide --version")
    assert_match "siltide", shell_output("#{bin}/siltide --demo --once")
  end
end
