# Generated by scripts/update.sh from the v0.1.1 release; do not edit by hand.
class Siltide < Formula
  desc "Terminal monitor for GPUs, NPUs, and other AI accelerators"
  homepage "https://github.com/moezdil/siltide"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/moezdil/siltide/releases/download/v0.1.1/siltide-darwin-arm64"
      sha256 "ec9525384126bf9d90e3677d8e7109b91cbd59550e940910c780cc84f3229299"
    end
    on_intel do
      url "https://github.com/moezdil/siltide/releases/download/v0.1.1/siltide-darwin-amd64"
      sha256 "3530aa2df23f09d40f4b7cf663d69032ddd4504ba50c76398c8c7b7adebe4732"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/moezdil/siltide/releases/download/v0.1.1/siltide-linux-arm64"
      sha256 "d43aaeafb2e2edf19da610b004b8a660343a84ff3badfd3658848bc2248d2466"
    end
    on_intel do
      url "https://github.com/moezdil/siltide/releases/download/v0.1.1/siltide-linux-amd64"
      sha256 "daa52e279a24897e139843d0ee95e517cc8c379b92082ff70a0b9639ab5a1476"
    end
  end

  def install
    binary = Dir["siltide-*"].first
    chmod 0755, binary
    bin.install binary => "siltide"
    generate_completions_from_executable(bin/"siltide", "--completion")
    (man1/"siltide.1").write Utils.safe_popen_read(bin/"siltide", "--man")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/siltide --version")
    assert_match "siltide", shell_output("#{bin}/siltide --demo --once")
  end
end
