#!/bin/sh
# Renders Formula/siltide.rb from the newest siltide release: a stable release
# when one exists, otherwise the newest pre-release from main.
set -eu
repo=moezdil/siltide
tag=$(gh api "repos/$repo/releases" --jq '[.[] | select(.draft | not) | select(.prerelease | not)][0].tag_name // empty')
[ -n "$tag" ] || tag=$(gh api "repos/$repo/releases" --jq '[.[] | select(.draft | not)][0].tag_name')
version=${tag#v}
sums=$(gh release download "$tag" -R "$repo" -p checksums.txt -O -)
sha() { printf '%s\n' "$sums" | awk -v f="siltide-$1" '$2 == f { print $1 }'; }
cat > Formula/siltide.rb <<RUBY
# Generated by scripts/update.sh from the $tag release; do not edit by hand.
class Siltide < Formula
  desc "Terminal monitor for GPUs, NPUs, and other AI accelerators"
  homepage "https://github.com/$repo"
  version "$version"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/$repo/releases/download/$tag/siltide-darwin-arm64"
      sha256 "$(sha darwin-arm64)"
    end
    on_intel do
      url "https://github.com/$repo/releases/download/$tag/siltide-darwin-amd64"
      sha256 "$(sha darwin-amd64)"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/$repo/releases/download/$tag/siltide-linux-arm64"
      sha256 "$(sha linux-arm64)"
    end
    on_intel do
      url "https://github.com/$repo/releases/download/$tag/siltide-linux-amd64"
      sha256 "$(sha linux-amd64)"
    end
  end

  def install
    binary = Dir["siltide-*"].first
    chmod 0755, binary
    bin.install binary => "siltide"
    generate_completions_from_executable(bin/"siltide", "--completion")
    (man1/"siltide.1").write Utils.safe_popen_read(bin/"siltide", "--man")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/siltide --version")
    assert_match "siltide", shell_output("#{bin}/siltide --demo --once")
  end
end
RUBY
echo "rendered $tag"
