name: update
on:
  repository_dispatch:
    types: [release]
  schedule:
    - cron: "17 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  formula:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: scripts/update.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Formula
          if ! git diff --cached --quiet; then
            git commit -m "Update siltide to $(sed -n 's/.*version "\(.*\)"/\1/p' Formula/siltide.rb)"
            git push
          fi
